### ISSUE TITLE
Globe Builder geocoding feature seems broken

### ISSUE THREAD

**Issue by JohnFBagby** [GispoCoding/GlobeBuilder#25] opened 2024-05-05 16:04 UTC
After choosing the Geocoding tick box,  I entered “Madrid” into the search box, hit the search button but the box below shows no entries for me.  It’s as if the connection to the OpenStreetMap server doesn’t exist.  Here’s a screenshot.

![image](https://github.com/GispoCoding/GlobeBuilder/assets/168982685/788afe3b-839f-4c0d-a974-4da23ba0f042)

**Desktop (please complete the following information):**
 - Plugin:Globe Builder 0.6.0
 - QGIS 3.28
 - Python: [e.g. 3.8]
 - OS: Windows 10

**Comment by LKajan** [comment] 2024-05-06 12:43
Duplicate of #24

**Closed as not planned by LKajan** 2024-05-06 12:43 UTC
Labels: bug
